name: OpenCart
version: '3.9'

services:
  opencart:
    image: aamservices/opencart:latest
    container_name: opencart_app
    restart: always
    ports:
      - "8080:80"
    environment:
      OPENCART_DB_HOST: db
      OPENCART_DB_USER: oc
      OPENCART_DB_PASSWORD: "genby[eqkj"
      OPENCART_DB_NAME: opencart

  db:
    image: mariadb:10.5
    container_name: opencart_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "genby[eqkj"
      MYSQL_DATABASE: opencart
      MYSQL_USER: oc
      MYSQL_PASSWORD: "genby[eqkj"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: opencart_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "genby[eqkj"

volumes:
  db_data:
